sites:
    - url  : https://my.smart.com.ph/loginAuth
      form : form#FormSSOLogin
      find : accessToken
      user : mySmartID
      pass : Password

    - url  : https://accounts.globe.com.ph/login
      form : form#login
      find : loggedin_email
      user : username
      pass : password
